<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "res_users".
 *
 * @property int $id
 * @property bool $active
 * @property string $login
 * @property string $password
 * @property int $company_id
 * @property int $partner_id
 * @property string $create_date Created on
 * @property int $create_uid Created by
 * @property bool $share Share User
 * @property int $write_uid Last Updated by
 * @property string $write_date Last Updated on
 * @property string $signature Signature
 * @property int $action_id Home Action
 * @property string $password_crypt Encrypted Password
 * @property int $alias_id Alias
 * @property bool $chatter_needaction_auto Automatically set needaction as Read
 * @property int $sale_team_id Sales Team
 * @property int $store_id Store
 * @property string $password_hash
 * @property int $x_location_id Ubicación actual
 * @property string $password_write_date Latest password update
 *
 * @property AccountAccount[] $accountAccounts
 * @property AccountAccount[] $accountAccounts0
 * @property AccountAccountBudget[] $accountAccountBudgets
 * @property AccountAccountBudget[] $accountAccountBudgets0
 * @property AccountAccountTag[] $accountAccountTags
 * @property AccountAccountTag[] $accountAccountTags0
 * @property AccountAccountTemplate[] $accountAccountTemplates
 * @property AccountAccountTemplate[] $accountAccountTemplates0
 * @property AccountAccountType[] $accountAccountTypes
 * @property AccountAccountType[] $accountAccountTypes0
 * @property AccountAgedTrialBalance[] $accountAgedTrialBalances
 * @property AccountAgedTrialBalance[] $accountAgedTrialBalances0
 * @property AccountAnalyticAccount[] $accountAnalyticAccounts
 * @property AccountAnalyticAccount[] $accountAnalyticAccounts0
 * @property AccountAnalyticChart[] $accountAnalyticCharts
 * @property AccountAnalyticChart[] $accountAnalyticCharts0
 * @property AccountAnalyticLine[] $accountAnalyticLines
 * @property AccountAnalyticLine[] $accountAnalyticLines0
 * @property AccountAnalyticLine[] $accountAnalyticLines1
 * @property AccountAnalyticTag[] $accountAnalyticTags
 * @property AccountAnalyticTag[] $accountAnalyticTags0
 * @property AccountAssetAsset[] $accountAssetAssets
 * @property AccountAssetAsset[] $accountAssetAssets0
 * @property AccountAssetBrand[] $accountAssetBrands
 * @property AccountAssetBrand[] $accountAssetBrands0
 * @property AccountAssetCategory[] $accountAssetCategories
 * @property AccountAssetCategory[] $accountAssetCategories0
 * @property AccountAssetDepreciationLine[] $accountAssetDepreciationLines
 * @property AccountAssetDepreciationLine[] $accountAssetDepreciationLines0
 * @property AccountAssetModel[] $accountAssetModels
 * @property AccountAssetModel[] $accountAssetModels0
 * @property AccountAssetState[] $accountAssetStates
 * @property AccountAssetState[] $accountAssetStates0
 * @property AccountAssetValidateWizard[] $accountAssetValidateWizards
 * @property AccountAssetValidateWizard[] $accountAssetValidateWizards0
 * @property AccountBalanceReport[] $accountBalanceReports
 * @property AccountBalanceReport[] $accountBalanceReports0
 * @property AccountBankAccountsWizard[] $accountBankAccountsWizards
 * @property AccountBankAccountsWizard[] $accountBankAccountsWizards0
 * @property AccountBankReconciliation[] $accountBankReconciliations
 * @property AccountBankReconciliation[] $accountBankReconciliations0
 * @property AccountBankReconciliationConfirmation[] $accountBankReconciliationConfirmations
 * @property AccountBankReconciliationConfirmation[] $accountBankReconciliationConfirmations0
 * @property AccountBankReconciliationLine[] $accountBankReconciliationLines
 * @property AccountBankReconciliationLine[] $accountBankReconciliationLines0
 * @property AccountBankStatement[] $accountBankStatements
 * @property AccountBankStatement[] $accountBankStatements0
 * @property AccountBankStatement[] $accountBankStatements1
 * @property AccountBankStatementCashbox[] $accountBankStatementCashboxes
 * @property AccountBankStatementCashbox[] $accountBankStatementCashboxes0
 * @property AccountBankStatementClosebalance[] $accountBankStatementClosebalances
 * @property AccountBankStatementClosebalance[] $accountBankStatementClosebalances0
 * @property AccountBankStatementImport[] $accountBankStatementImports
 * @property AccountBankStatementImport[] $accountBankStatementImports0
 * @property AccountBankStatementImportJournalCreation[] $accountBankStatementImportJournalCreations
 * @property AccountBankStatementImportJournalCreation[] $accountBankStatementImportJournalCreations0
 * @property AccountBankStatementLine[] $accountBankStatementLines
 * @property AccountBankStatementLine[] $accountBankStatementLines0
 * @property AccountCashClosing[] $accountCashClosings
 * @property AccountCashClosing[] $accountCashClosings0
 * @property AccountCashClosing[] $accountCashClosings1
 * @property AccountCashClosingPayments[] $accountCashClosingPayments
 * @property AccountCashClosingPayments[] $accountCashClosingPayments0
 * @property AccountCashboxLine[] $accountCashboxLines
 * @property AccountCashboxLine[] $accountCashboxLines0
 * @property AccountCashmanagementApplication[] $accountCashmanagementApplications
 * @property AccountCashmanagementApplication[] $accountCashmanagementApplications0
 * @property AccountCashmanagementApplicationFile[] $accountCashmanagementApplicationFiles
 * @property AccountCashmanagementApplicationFile[] $accountCashmanagementApplicationFiles0
 * @property AccountCashmanagementCatalogue[] $accountCashmanagementCatalogues
 * @property AccountCashmanagementCatalogue[] $accountCashmanagementCatalogues0
 * @property AccountCashmanagementCatalogueType[] $accountCashmanagementCatalogueTypes
 * @property AccountCashmanagementCatalogueType[] $accountCashmanagementCatalogueTypes0
 * @property AccountCashmanagementExtension[] $accountCashmanagementExtensions
 * @property AccountCashmanagementExtension[] $accountCashmanagementExtensions0
 * @property AccountCashmanagementFileWizard[] $accountCashmanagementFileWizards
 * @property AccountCashmanagementFileWizard[] $accountCashmanagementFileWizards0
 * @property AccountCashmanagementFormat[] $accountCashmanagementFormats
 * @property AccountCashmanagementFormat[] $accountCashmanagementFormats0
 * @property AccountCashmanagementFormatField[] $accountCashmanagementFormatFields
 * @property AccountCashmanagementFormatField[] $accountCashmanagementFormatFields0
 * @property AccountCashmanagementFormatFieldchild[] $accountCashmanagementFormatFieldchildren
 * @property AccountCashmanagementFormatFieldchild[] $accountCashmanagementFormatFieldchildren0
 * @property AccountCashmanagementWizard[] $accountCashmanagementWizards
 * @property AccountCashmanagementWizard[] $accountCashmanagementWizards0
 * @property AccountChartTemplate[] $accountChartTemplates
 * @property AccountChartTemplate[] $accountChartTemplates0
 * @property AccountCommonAccountReport[] $accountCommonAccountReports
 * @property AccountCommonAccountReport[] $accountCommonAccountReports0
 * @property AccountCommonPartnerReport[] $accountCommonPartnerReports
 * @property AccountCommonPartnerReport[] $accountCommonPartnerReports0
 * @property AccountCommonReport[] $accountCommonReports
 * @property AccountCommonReport[] $accountCommonReports0
 * @property AccountConfigSettings[] $accountConfigSettings
 * @property AccountConfigSettings[] $accountConfigSettings0
 * @property AccountDirectPaymentLine[] $accountDirectPaymentLines
 * @property AccountDirectPaymentLine[] $accountDirectPaymentLines0
 * @property AccountDocumentTemplate[] $accountDocumentTemplates
 * @property AccountDocumentTemplate[] $accountDocumentTemplates0
 * @property AccountDocumentTemplateLine[] $accountDocumentTemplateLines
 * @property AccountDocumentTemplateLine[] $accountDocumentTemplateLines0
 * @property AccountFinancialReport[] $accountFinancialReports
 * @property AccountFinancialReport[] $accountFinancialReports0
 * @property AccountFinancialWizard[] $accountFinancialWizards
 * @property AccountFinancialWizard[] $accountFinancialWizards0
 * @property AccountFiscalPosition[] $accountFiscalPositions
 * @property AccountFiscalPosition[] $accountFiscalPositions0
 * @property AccountFiscalPositionAccount[] $accountFiscalPositionAccounts
 * @property AccountFiscalPositionAccount[] $accountFiscalPositionAccounts0
 * @property AccountFiscalPositionAccountTemplate[] $accountFiscalPositionAccountTemplates
 * @property AccountFiscalPositionAccountTemplate[] $accountFiscalPositionAccountTemplates0
 * @property AccountFiscalPositionTax[] $accountFiscalPositionTaxes
 * @property AccountFiscalPositionTax[] $accountFiscalPositionTaxes0
 * @property AccountFiscalPositionTaxTemplate[] $accountFiscalPositionTaxTemplates
 * @property AccountFiscalPositionTaxTemplate[] $accountFiscalPositionTaxTemplates0
 * @property AccountFiscalPositionTemplate[] $accountFiscalPositionTemplates
 * @property AccountFiscalPositionTemplate[] $accountFiscalPositionTemplates0
 * @property AccountInvoice[] $accountInvoices
 * @property AccountInvoice[] $accountInvoices0
 * @property AccountInvoice[] $accountInvoices1
 * @property AccountInvoiceAutomaticLog[] $accountInvoiceAutomaticLogs
 * @property AccountInvoiceAutomaticLog[] $accountInvoiceAutomaticLogs0
 * @property AccountInvoiceCancel[] $accountInvoiceCancels
 * @property AccountInvoiceCancel[] $accountInvoiceCancels0
 * @property AccountInvoiceConfiguration[] $accountInvoiceConfigurations
 * @property AccountInvoiceConfiguration[] $accountInvoiceConfigurations0
 * @property AccountInvoiceConfirm[] $accountInvoiceConfirms
 * @property AccountInvoiceConfirm[] $accountInvoiceConfirms0
 * @property AccountInvoiceLine[] $accountInvoiceLines
 * @property AccountInvoiceLine[] $accountInvoiceLines0
 * @property AccountInvoiceRefund[] $accountInvoiceRefunds
 * @property AccountInvoiceRefund[] $accountInvoiceRefunds0
 * @property AccountInvoiceRetention[] $accountInvoiceRetentions
 * @property AccountInvoiceRetention[] $accountInvoiceRetentions0
 * @property AccountInvoiceTax[] $accountInvoiceTaxes
 * @property AccountInvoiceTax[] $accountInvoiceTaxes0
 * @property AccountInvoicesRefunds[] $accountInvoicesRefunds
 * @property AccountInvoicesRefunds[] $accountInvoicesRefunds0
 * @property AccountJournal[] $accountJournals
 * @property AccountJournal[] $accountJournals0
 * @property AccountMove[] $accountMoves
 * @property AccountMove[] $accountMoves0
 * @property AccountMove[] $accountMoves1
 * @property AccountMoveLine[] $accountMoveLines
 * @property AccountMoveLine[] $accountMoveLines0
 * @property AccountMoveLineReconcile[] $accountMoveLineReconciles
 * @property AccountMoveLineReconcile[] $accountMoveLineReconciles0
 * @property AccountMoveLineReconcileWriteoff[] $accountMoveLineReconcileWriteoffs
 * @property AccountMoveLineReconcileWriteoff[] $accountMoveLineReconcileWriteoffs0
 * @property AccountMoveReversal[] $accountMoveReversals
 * @property AccountMoveReversal[] $accountMoveReversals0
 * @property AccountMoveTemplate[] $accountMoveTemplates
 * @property AccountMoveTemplate[] $accountMoveTemplates0
 * @property AccountMoveTemplateLine[] $accountMoveTemplateLines
 * @property AccountMoveTemplateLine[] $accountMoveTemplateLines0
 * @property AccountOperationTemplate[] $accountOperationTemplates
 * @property AccountOperationTemplate[] $accountOperationTemplates0
 * @property AccountOverdueMailingWizard[] $accountOverdueMailingWizards
 * @property AccountOverdueMailingWizard[] $accountOverdueMailingWizards0
 * @property AccountPartialReconcile[] $accountPartialReconciles
 * @property AccountPartialReconcile[] $accountPartialReconciles0
 * @property AccountPayment[] $accountPayments
 * @property AccountPayment[] $accountPayments0
 * @property AccountPayment[] $accountPayments1
 * @property AccountPaymentCheckDeposit[] $accountPaymentCheckDeposits
 * @property AccountPaymentCheckDeposit[] $accountPaymentCheckDeposits0
 * @property AccountPaymentLine[] $accountPaymentLines
 * @property AccountPaymentLine[] $accountPaymentLines0
 * @property AccountPaymentMethod[] $accountPaymentMethods
 * @property AccountPaymentMethod[] $accountPaymentMethods0
 * @property AccountPaymentTerm[] $accountPaymentTerms
 * @property AccountPaymentTerm[] $accountPaymentTerms0
 * @property AccountPaymentTermLine[] $accountPaymentTermLines
 * @property AccountPaymentTermLine[] $accountPaymentTermLines0
 * @property AccountRegisterPayments[] $accountRegisterPayments
 * @property AccountRegisterPayments[] $accountRegisterPayments0
 * @property AccountReportGeneralLedger[] $accountReportGeneralLedgers
 * @property AccountReportGeneralLedger[] $accountReportGeneralLedgers0
 * @property AccountRetentionCommission[] $accountRetentionCommissions
 * @property AccountRetentionCommission[] $accountRetentionCommissions0
 * @property AccountRetentionCommissionLine[] $accountRetentionCommissionLines
 * @property AccountRetentionCommissionLine[] $accountRetentionCommissionLines0
 * @property AccountSriPaymentWay[] $accountSriPaymentWays
 * @property AccountSriPaymentWay[] $accountSriPaymentWays0
 * @property AccountTax[] $accountTaxes
 * @property AccountTax[] $accountTaxes0
 * @property AccountTaxGroup[] $accountTaxGroups
 * @property AccountTaxGroup[] $accountTaxGroups0
 * @property AccountTaxTemplate[] $accountTaxTemplates
 * @property AccountTaxTemplate[] $accountTaxTemplates0
 * @property AccountUnreconcile[] $accountUnreconciles
 * @property AccountUnreconcile[] $accountUnreconciles0
 * @property AccountVoucher[] $accountVouchers
 * @property AccountVoucher[] $accountVouchers0
 * @property AccountVoucherLine[] $accountVoucherLines
 * @property AccountVoucherLine[] $accountVoucherLines0
 * @property AccountingReport[] $accountingReports
 * @property AccountingReport[] $accountingReports0
 * @property AdmissionAnalysis[] $admissionAnalyses
 * @property AdmissionAnalysis[] $admissionAnalyses0
 * @property AssetDepreciationConfirmationWizard[] $assetDepreciationConfirmationWizards
 * @property AssetDepreciationConfirmationWizard[] $assetDepreciationConfirmationWizards0
 * @property AssetModify[] $assetModifies
 * @property AssetModify[] $assetModifies0
 * @property AtsPeriod[] $atsPeriods
 * @property AtsPeriod[] $atsPeriods0
 * @property BankFile[] $bankFiles
 * @property BankFile[] $bankFiles0
 * @property BankFileJep[] $bankFileJeps
 * @property BankFileJep[] $bankFileJeps0
 * @property BankFileJepPayments[] $bankFileJepPayments
 * @property BankFileJepPayments[] $bankFileJepPayments0
 * @property BankFilePayments[] $bankFilePayments
 * @property BankFilePayments[] $bankFilePayments0
 * @property BankFilePichincha[] $bankFilePichinchas
 * @property BankFilePichincha[] $bankFilePichinchas0
 * @property BankFileProdubanco[] $bankFileProdubancos
 * @property BankFileProdubanco[] $bankFileProdubancos0
 * @property BankFileProdubancoPayment[] $bankFileProdubancoPayments
 * @property BankFileProdubancoPayment[] $bankFileProdubancoPayments0
 * @property BarcodeNomenclature[] $barcodeNomenclatures
 * @property BarcodeNomenclature[] $barcodeNomenclatures0
 * @property BarcodeRule[] $barcodeRules
 * @property BarcodeRule[] $barcodeRules0
 * @property BaseActionRule[] $baseActionRules
 * @property BaseActionRule[] $baseActionRules0
 * @property BaseActionRule[] $baseActionRules1
 * @property BaseActionRuleLeadTest[] $baseActionRuleLeadTests
 * @property BaseActionRuleLeadTest[] $baseActionRuleLeadTests0
 * @property BaseActionRuleLeadTest[] $baseActionRuleLeadTests1
 * @property BaseConfigSettings[] $baseConfigSettings
 * @property BaseConfigSettings[] $baseConfigSettings0
 * @property BaseConfigSettings[] $baseConfigSettings1
 * @property BaseImportImport[] $baseImportImports
 * @property BaseImportImport[] $baseImportImports0
 * @property BaseImportTestsModelsChar[] $baseImportTestsModelsChars
 * @property BaseImportTestsModelsChar[] $baseImportTestsModelsChars0
 * @property BaseImportTestsModelsCharNoreadonly[] $baseImportTestsModelsCharNoreadonlies
 * @property BaseImportTestsModelsCharNoreadonly[] $baseImportTestsModelsCharNoreadonlies0
 * @property BaseImportTestsModelsCharReadonly[] $baseImportTestsModelsCharReadonlies
 * @property BaseImportTestsModelsCharReadonly[] $baseImportTestsModelsCharReadonlies0
 * @property BaseImportTestsModelsCharRequired[] $baseImportTestsModelsCharRequireds
 * @property BaseImportTestsModelsCharRequired[] $baseImportTestsModelsCharRequireds0
 * @property BaseImportTestsModelsCharStates[] $baseImportTestsModelsCharStates
 * @property BaseImportTestsModelsCharStates[] $baseImportTestsModelsCharStates0
 * @property BaseImportTestsModelsCharStillreadonly[] $baseImportTestsModelsCharStillreadonlies
 * @property BaseImportTestsModelsCharStillreadonly[] $baseImportTestsModelsCharStillreadonlies0
 * @property BaseImportTestsModelsM2o[] $baseImportTestsModelsM2os
 * @property BaseImportTestsModelsM2o[] $baseImportTestsModelsM2os0
 * @property BaseImportTestsModelsM2oRelated[] $baseImportTestsModelsM2oRelateds
 * @property BaseImportTestsModelsM2oRelated[] $baseImportTestsModelsM2oRelateds0
 * @property BaseImportTestsModelsM2oRequired[] $baseImportTestsModelsM2oRequireds
 * @property BaseImportTestsModelsM2oRequired[] $baseImportTestsModelsM2oRequireds0
 * @property BaseImportTestsModelsM2oRequiredRelated[] $baseImportTestsModelsM2oRequiredRelateds
 * @property BaseImportTestsModelsM2oRequiredRelated[] $baseImportTestsModelsM2oRequiredRelateds0
 * @property BaseImportTestsModelsO2m[] $baseImportTestsModelsO2ms
 * @property BaseImportTestsModelsO2m[] $baseImportTestsModelsO2ms0
 * @property BaseImportTestsModelsO2mChild[] $baseImportTestsModelsO2mChildren
 * @property BaseImportTestsModelsO2mChild[] $baseImportTestsModelsO2mChildren0
 * @property BaseImportTestsModelsPreview[] $baseImportTestsModelsPreviews
 * @property BaseImportTestsModelsPreview[] $baseImportTestsModelsPreviews0
 * @property BaseLanguageExport[] $baseLanguageExports
 * @property BaseLanguageExport[] $baseLanguageExports0
 * @property BaseLanguageImport[] $baseLanguageImports
 * @property BaseLanguageImport[] $baseLanguageImports0
 * @property BaseLanguageInstall[] $baseLanguageInstalls
 * @property BaseLanguageInstall[] $baseLanguageInstalls0
 * @property BaseModuleConfiguration[] $baseModuleConfigurations
 * @property BaseModuleConfiguration[] $baseModuleConfigurations0
 * @property BaseModuleUpdate[] $baseModuleUpdates
 * @property BaseModuleUpdate[] $baseModuleUpdates0
 * @property BaseModuleUpgrade[] $baseModuleUpgrades
 * @property BaseModuleUpgrade[] $baseModuleUpgrades0
 * @property BaseSetupTerminology[] $baseSetupTerminologies
 * @property BaseSetupTerminology[] $baseSetupTerminologies0
 * @property BaseUpdateTranslations[] $baseUpdateTranslations
 * @property BaseUpdateTranslations[] $baseUpdateTranslations0
 * @property BizbankPaymentWizard[] $bizbankPaymentWizards
 * @property BizbankPaymentWizard[] $bizbankPaymentWizards0
 * @property BoardCreate[] $boardCreates
 * @property BoardCreate[] $boardCreates0
 * @property BusBus[] $busBuses
 * @property BusBus[] $busBuses0
 * @property BusPresence[] $busPresences
 * @property BusPresence[] $busPresences0
 * @property BusPresence $busPresence
 * @property CalendarAlarm[] $calendarAlarms
 * @property CalendarAlarm[] $calendarAlarms0
 * @property CalendarAttendee[] $calendarAttendees
 * @property CalendarAttendee[] $calendarAttendees0
 * @property CalendarContacts[] $calendarContacts
 * @property CalendarContacts[] $calendarContacts0
 * @property CalendarContacts[] $calendarContacts1
 * @property CalendarEvent[] $calendarEvents
 * @property CalendarEvent[] $calendarEvents0
 * @property CalendarEvent[] $calendarEvents1
 * @property CalendarEventType[] $calendarEventTypes
 * @property CalendarEventType[] $calendarEventTypes0
 * @property CancelRetentionConfirm[] $cancelRetentionConfirms
 * @property CancelRetentionConfirm[] $cancelRetentionConfirms0
 * @property CashBoxIn[] $cashBoxIns
 * @property CashBoxIn[] $cashBoxIns0
 * @property CashBoxOut[] $cashBoxOuts
 * @property CashBoxOut[] $cashBoxOuts0
 * @property CashmanagementConfigSettings[] $cashmanagementConfigSettings
 * @property CashmanagementConfigSettings[] $cashmanagementConfigSettings0
 * @property ChangePasswordUser[] $changePasswordUsers
 * @property ChangePasswordUser[] $changePasswordUsers0
 * @property ChangePasswordUser[] $changePasswordUsers1
 * @property ChangePasswordWizard[] $changePasswordWizards
 * @property ChangePasswordWizard[] $changePasswordWizards0
 * @property CollegeDataWizard[] $collegeDataWizards
 * @property CollegeDataWizard[] $collegeDataWizards0
 * @property CostCentre[] $costCentres
 * @property CostCentre[] $costCentres0
 * @property CostCentreAssetLine[] $costCentreAssetLines
 * @property CostCentreAssetLine[] $costCentreAssetLines0
 * @property CostCentreEmployee[] $costCentreEmployees
 * @property CostCentreEmployee[] $costCentreEmployees0
 * @property CostCentreMove[] $costCentreMoves
 * @property CostCentreMove[] $costCentreMoves0
 * @property CostCentreUplev[] $costCentreUplevs
 * @property CostCentreUplev[] $costCentreUplevs0
 * @property CrmTeam[] $crmTeams
 * @property CrmTeam[] $crmTeams0
 * @property CrmTeam[] $crmTeams1
 * @property CustomerWizardInvoiceImp[] $customerWizardInvoiceImps
 * @property CustomerWizardInvoiceImp[] $customerWizardInvoiceImps0
 * @property CustomerWizardPaymentConciliation[] $customerWizardPaymentConciliations
 * @property CustomerWizardPaymentConciliation[] $customerWizardPaymentConciliations0
 * @property CustomerWizardPrepaymentConciliation[] $customerWizardPrepaymentConciliations
 * @property CustomerWizardPrepaymentConciliation[] $customerWizardPrepaymentConciliations0
 * @property DateRange[] $dateRanges
 * @property DateRange[] $dateRanges0
 * @property DateRangeGenerator[] $dateRangeGenerators
 * @property DateRangeGenerator[] $dateRangeGenerators0
 * @property DateRangeType[] $dateRangeTypes
 * @property DateRangeType[] $dateRangeTypes0
 * @property DecimalPrecision[] $decimalPrecisions
 * @property DecimalPrecision[] $decimalPrecisions0
 * @property DecimalPrecisionTest[] $decimalPrecisionTests
 * @property DecimalPrecisionTest[] $decimalPrecisionTests0
 * @property ElectronicConfiguration[] $electronicConfigurations
 * @property ElectronicConfiguration[] $electronicConfigurations0
 * @property EmailTemplatePreview[] $emailTemplatePreviews
 * @property EmailTemplatePreview[] $emailTemplatePreviews0
 * @property EnrollmentPaymentMethod[] $enrollmentPaymentMethods
 * @property EnrollmentPaymentMethod[] $enrollmentPaymentMethods0
 * @property FetchmailConfigSettings[] $fetchmailConfigSettings
 * @property FetchmailConfigSettings[] $fetchmailConfigSettings0
 * @property FetchmailServer[] $fetchmailServers
 * @property FetchmailServer[] $fetchmailServers0
 * @property FiscalAuthorizationRank[] $fiscalAuthorizationRanks
 * @property FiscalAuthorizationRank[] $fiscalAuthorizationRanks0
 * @property GenerateContractReportWizard[] $generateContractReportWizards
 * @property GenerateContractReportWizard[] $generateContractReportWizards0
 * @property HrConfigSettings[] $hrConfigSettings
 * @property HrConfigSettings[] $hrConfigSettings0
 * @property HrContract[] $hrContracts
 * @property HrContract[] $hrContracts0
 * @property HrContractType[] $hrContractTypes
 * @property HrContractType[] $hrContractTypes0
 * @property HrContributionRegister[] $hrContributionRegisters
 * @property HrContributionRegister[] $hrContributionRegisters0
 * @property HrD3erSocialBenefit[] $hrD3erSocialBenefits
 * @property HrD3erSocialBenefit[] $hrD3erSocialBenefits0
 * @property HrD3erSocialBenefitLine[] $hrD3erSocialBenefitLines
 * @property HrD3erSocialBenefitLine[] $hrD3erSocialBenefitLines0
 * @property HrDepartment[] $hrDepartments
 * @property HrDepartment[] $hrDepartments0
 * @property HrEmployee[] $hrEmployees
 * @property HrEmployee[] $hrEmployees0
 * @property HrEmployeeCategory[] $hrEmployeeCategories
 * @property HrEmployeeCategory[] $hrEmployeeCategories0
 * @property HrEmployeeChildren[] $hrEmployeeChildrens
 * @property HrEmployeeChildren[] $hrEmployeeChildrens0
 * @property HrEmployeeExpenses[] $hrEmployeeExpenses
 * @property HrEmployeeExpenses[] $hrEmployeeExpenses0
 * @property HrEmployeeExpensesLines[] $hrEmployeeExpensesLines
 * @property HrEmployeeExpensesLines[] $hrEmployeeExpensesLines0
 * @property HrEmployeeInstitute[] $hrEmployeeInstitutes
 * @property HrEmployeeInstitute[] $hrEmployeeInstitutes0
 * @property HrEmployeeTitle[] $hrEmployeeTitles
 * @property HrEmployeeTitle[] $hrEmployeeTitles0
 * @property HrEmployeeWorktime[] $hrEmployeeWorktimes
 * @property HrEmployeeWorktime[] $hrEmployeeWorktimes0
 * @property HrEquipment[] $hrEquipments
 * @property HrEquipment[] $hrEquipments0
 * @property HrEquipment[] $hrEquipments1
 * @property HrEquipmentCategory[] $hrEquipmentCategories
 * @property HrEquipmentCategory[] $hrEquipmentCategories0
 * @property HrEquipmentCategory[] $hrEquipmentCategories1
 * @property HrEquipmentConfigSettings[] $hrEquipmentConfigSettings
 * @property HrEquipmentConfigSettings[] $hrEquipmentConfigSettings0
 * @property HrEquipmentRequest[] $hrEquipmentRequests
 * @property HrEquipmentRequest[] $hrEquipmentRequests0
 * @property HrEquipmentRequest[] $hrEquipmentRequests1
 * @property HrEquipmentStage[] $hrEquipmentStages
 * @property HrEquipmentStage[] $hrEquipmentStages0
 * @property HrExpense[] $hrExpenses
 * @property HrExpense[] $hrExpenses0
 * @property HrExpenseRefuseWizard[] $hrExpenseRefuseWizards
 * @property HrExpenseRefuseWizard[] $hrExpenseRefuseWizards0
 * @property HrExpenseReplicateWizard[] $hrExpenseReplicateWizards
 * @property HrExpenseReplicateWizard[] $hrExpenseReplicateWizards0
 * @property HrExpenseTypes[] $hrExpenseTypes
 * @property HrExpenseTypes[] $hrExpenseTypes0
 * @property HrHolidays[] $hrHolidays
 * @property HrHolidays[] $hrHolidays0
 * @property HrHolidays[] $hrHolidays1
 * @property HrHolidaysStatus[] $hrHolidaysStatuses
 * @property HrHolidaysStatus[] $hrHolidaysStatuses0
 * @property HrHolidaysSummaryDept[] $hrHolidaysSummaryDepts
 * @property HrHolidaysSummaryDept[] $hrHolidaysSummaryDepts0
 * @property HrHolidaysSummaryEmployee[] $hrHolidaysSummaryEmployees
 * @property HrHolidaysSummaryEmployee[] $hrHolidaysSummaryEmployees0
 * @property HrJob[] $hrJobs
 * @property HrJob[] $hrJobs0
 * @property HrLoan[] $hrLoans
 * @property HrLoan[] $hrLoans0
 * @property HrLoanLine[] $hrLoanLines
 * @property HrLoanLine[] $hrLoanLines0
 * @property HrLoanPaymentWizard[] $hrLoanPaymentWizards
 * @property HrLoanPaymentWizard[] $hrLoanPaymentWizards0
 * @property HrPayrollConfigSettings[] $hrPayrollConfigSettings
 * @property HrPayrollConfigSettings[] $hrPayrollConfigSettings0
 * @property HrPayrollStructure[] $hrPayrollStructures
 * @property HrPayrollStructure[] $hrPayrollStructures0
 * @property HrPayslip[] $hrPayslips
 * @property HrPayslip[] $hrPayslips0
 * @property HrPayslipBankFile[] $hrPayslipBankFiles
 * @property HrPayslipBankFile[] $hrPayslipBankFiles0
 * @property HrPayslipDiscountLines[] $hrPayslipDiscountLines
 * @property HrPayslipDiscountLines[] $hrPayslipDiscountLines0
 * @property HrPayslipEmployees[] $hrPayslipEmployees
 * @property HrPayslipEmployees[] $hrPayslipEmployees0
 * @property HrPayslipInput[] $hrPayslipInputs
 * @property HrPayslipInput[] $hrPayslipInputs0
 * @property HrPayslipLine[] $hrPayslipLines
 * @property HrPayslipLine[] $hrPayslipLines0
 * @property HrPayslipReport[] $hrPayslipReports
 * @property HrPayslipReport[] $hrPayslipReports0
 * @property HrPayslipRun[] $hrPayslipRuns
 * @property HrPayslipRun[] $hrPayslipRuns0
 * @property HrPayslipSendmailWizard[] $hrPayslipSendmailWizards
 * @property HrPayslipSendmailWizard[] $hrPayslipSendmailWizards0
 * @property HrPayslipWorkedDays[] $hrPayslipWorkedDays
 * @property HrPayslipWorkedDays[] $hrPayslipWorkedDays0
 * @property HrRentTaxConfig[] $hrRentTaxConfigs
 * @property HrRentTaxConfig[] $hrRentTaxConfigs0
 * @property HrRentTaxLines[] $hrRentTaxLines
 * @property HrRentTaxLines[] $hrRentTaxLines0
 * @property HrRuleInput[] $hrRuleInputs
 * @property HrRuleInput[] $hrRuleInputs0
 * @property HrSalaryProvisions[] $hrSalaryProvisions
 * @property HrSalaryProvisions[] $hrSalaryProvisions0
 * @property HrSalaryRule[] $hrSalaryRules
 * @property HrSalaryRule[] $hrSalaryRules0
 * @property HrSalaryRuleCategory[] $hrSalaryRuleCategories
 * @property HrSalaryRuleCategory[] $hrSalaryRuleCategories0
 * @property HrSalarySummary[] $hrSalarySummaries
 * @property HrSalarySummary[] $hrSalarySummaries0
 * @property HrSocialBenefitConfig[] $hrSocialBenefitConfigs
 * @property HrSocialBenefitConfig[] $hrSocialBenefitConfigs0
 * @property HrSocialBenefitPaymentWizard[] $hrSocialBenefitPaymentWizards
 * @property HrSocialBenefitPaymentWizard[] $hrSocialBenefitPaymentWizards0
 * @property HrSocialBenefitWizard[] $hrSocialBenefitWizards
 * @property HrSocialBenefitWizard[] $hrSocialBenefitWizards0
 * @property HrVariableDiscount[] $hrVariableDiscounts
 * @property HrVariableDiscount[] $hrVariableDiscounts0
 * @property HrVariableIncome[] $hrVariableIncomes
 * @property HrVariableIncome[] $hrVariableIncomes0
 * @property HummingbirdConfig[] $hummingbirdConfigs
 * @property HummingbirdConfig[] $hummingbirdConfigs0
 * @property ImportPaymentFileWizard[] $importPaymentFileWizards
 * @property ImportPaymentFileWizard[] $importPaymentFileWizards0
 * @property InscriptionGenerateWizard[] $inscriptionGenerateWizards
 * @property InscriptionGenerateWizard[] $inscriptionGenerateWizards0
 * @property InscriptionGenerateWizardLines[] $inscriptionGenerateWizardLines
 * @property InscriptionGenerateWizardLines[] $inscriptionGenerateWizardLines0
 * @property InscriptionOptionWizard[] $inscriptionOptionWizards
 * @property InscriptionOptionWizard[] $inscriptionOptionWizards0
 * @property IntegralisProductType[] $integralisProductTypes
 * @property IntegralisProductType[] $integralisProductTypes0
 * @property InvoiceElectronicReceived[] $invoiceElectronicReceiveds
 * @property InvoiceElectronicReceived[] $invoiceElectronicReceiveds0
 * @property IrActClient[] $irActClients
 * @property IrActClient[] $irActClients0
 * @property IrActReportXml[] $irActReportXmls
 * @property IrActReportXml[] $irActReportXmls0
 * @property IrActServer[] $irActServers
 * @property IrActServer[] $irActServers0
 * @property IrActUrl[] $irActUrls
 * @property IrActUrl[] $irActUrls0
 * @property IrActWindow[] $irActWindows
 * @property IrActWindow[] $irActWindows0
 * @property IrActWindowView[] $irActWindowViews
 * @property IrActWindowView[] $irActWindowViews0
 * @property IrActions[] $irActions
 * @property IrActions[] $irActions0
 * @property IrActions[] $irActions1
 * @property IrActions[] $irActions2
 * @property IrActionsTodo[] $irActionsTodos
 * @property IrActionsTodo[] $irActionsTodos0
 * @property IrAttachment[] $irAttachments
 * @property IrAttachment[] $irAttachments0
 * @property IrAutovacuum[] $irAutovacuums
 * @property IrAutovacuum[] $irAutovacuums0
 * @property IrConfigParameter[] $irConfigParameters
 * @property IrConfigParameter[] $irConfigParameters0
 * @property IrCron[] $irCrons
 * @property IrCron[] $irCrons0
 * @property IrCron[] $irCrons1
 * @property IrExports[] $irExports
 * @property IrExports[] $irExports0
 * @property IrExportsLine[] $irExportsLines
 * @property IrExportsLine[] $irExportsLines0
 * @property IrFilters[] $irFilters
 * @property IrFilters[] $irFilters0
 * @property IrFilters[] $irFilters1
 * @property IrLogging[] $irLoggings
 * @property IrMailServer[] $irMailServers
 * @property IrMailServer[] $irMailServers0
 * @property IrModel[] $irModels
 * @property IrModel[] $irModels0
 * @property IrModelAccess[] $irModelAccesses
 * @property IrModelAccess[] $irModelAccesses0
 * @property IrModelConstraint[] $irModelConstraints
 * @property IrModelConstraint[] $irModelConstraints0
 * @property IrModelData[] $irModelDatas
 * @property IrModelData[] $irModelDatas0
 * @property IrModelFields[] $irModelFields
 * @property IrModelFields[] $irModelFields0
 * @property IrModelRelation[] $irModelRelations
 * @property IrModelRelation[] $irModelRelations0
 * @property IrModuleCategory[] $irModuleCategories
 * @property IrModuleCategory[] $irModuleCategories0
 * @property IrModuleModule[] $irModuleModules
 * @property IrModuleModule[] $irModuleModules0
 * @property IrModuleModuleDependency[] $irModuleModuleDependencies
 * @property IrModuleModuleDependency[] $irModuleModuleDependencies0
 * @property IrProperty[] $irProperties
 * @property IrProperty[] $irProperties0
 * @property IrRule[] $irRules
 * @property IrRule[] $irRules0
 * @property IrSequence[] $irSequences
 * @property IrSequence[] $irSequences0
 * @property IrSequenceDateRange[] $irSequenceDateRanges
 * @property IrSequenceDateRange[] $irSequenceDateRanges0
 * @property IrServerObjectLines[] $irServerObjectLines
 * @property IrServerObjectLines[] $irServerObjectLines0
 * @property IrUiMenu[] $irUiMenus
 * @property IrUiMenu[] $irUiMenus0
 * @property IrUiView[] $irUiViews
 * @property IrUiView[] $irUiViews0
 * @property IrUiViewCustom[] $irUiViewCustoms
 * @property IrUiViewCustom[] $irUiViewCustoms0
 * @property IrUiViewCustom[] $irUiViewCustoms1
 * @property IrValues[] $irValues
 * @property IrValues[] $irValues0
 * @property IrValues[] $irValues1
 * @property IssueBook[] $issueBooks
 * @property IssueBook[] $issueBooks0
 * @property LineInvoiceAssetLine[] $lineInvoiceAssetLines
 * @property LineInvoiceAssetLine[] $lineInvoiceAssetLines0
 * @property MailAlias[] $mailAliases
 * @property MailAlias[] $mailAliases0
 * @property MailAlias[] $mailAliases1
 * @property MailChannel[] $mailChannels
 * @property MailChannel[] $mailChannels0
 * @property MailChannelPartner[] $mailChannelPartners
 * @property MailChannelPartner[] $mailChannelPartners0
 * @property MailComposeMessage[] $mailComposeMessages
 * @property MailComposeMessage[] $mailComposeMessages0
 * @property MailMail[] $mailMails
 * @property MailMail[] $mailMails0
 * @property MailMessage[] $mailMessages
 * @property MailMessage[] $mailMessages0
 * @property MailMessageSubtype[] $mailMessageSubtypes
 * @property MailMessageSubtype[] $mailMessageSubtypes0
 * @property MailShortcode[] $mailShortcodes
 * @property MailShortcode[] $mailShortcodes0
 * @property MailTemplate[] $mailTemplates
 * @property MailTemplate[] $mailTemplates0
 * @property MailTrackingValue[] $mailTrackingValues
 * @property MailTrackingValue[] $mailTrackingValues0
 * @property MailWizardInvite[] $mailWizardInvites
 * @property MailWizardInvite[] $mailWizardInvites0
 * @property MakeProcurement[] $makeProcurements
 * @property MakeProcurement[] $makeProcurements0
 * @property MarketingConfigSettings[] $marketingConfigSettings
 * @property MarketingConfigSettings[] $marketingConfigSettings0
 * @property OpAchievement[] $opAchievements
 * @property OpAchievement[] $opAchievements0
 * @property OpAchievementType[] $opAchievementTypes
 * @property OpAchievementType[] $opAchievementTypes0
 * @property OpActivity[] $opActivities
 * @property OpActivity[] $opActivities0
 * @property OpActivityType[] $opActivityTypes
 * @property OpActivityType[] $opActivityTypes0
 * @property OpAdmission[] $opAdmissions
 * @property OpAdmission[] $opAdmissions0
 * @property OpAdmissionRegister[] $opAdmissionRegisters
 * @property OpAdmissionRegister[] $opAdmissionRegisters0
 * @property OpAllStudent[] $opAllStudents
 * @property OpAllStudent[] $opAllStudents0
 * @property OpAsset[] $opAssets
 * @property OpAsset[] $opAssets0
 * @property OpAssignment[] $opAssignments
 * @property OpAssignment[] $opAssignments0
 * @property OpAssignmentSubLine[] $opAssignmentSubLines
 * @property OpAssignmentSubLine[] $opAssignmentSubLines0
 * @property OpAssignmentType[] $opAssignmentTypes
 * @property OpAssignmentType[] $opAssignmentTypes0
 * @property OpAttendanceLine[] $opAttendanceLines
 * @property OpAttendanceLine[] $opAttendanceLines0
 * @property OpAttendanceRegister[] $opAttendanceRegisters
 * @property OpAttendanceRegister[] $opAttendanceRegisters0
 * @property OpAttendanceSheet[] $opAttendanceSheets
 * @property OpAttendanceSheet[] $opAttendanceSheets0
 * @property OpAuthor[] $opAuthors
 * @property OpAuthor[] $opAuthors0
 * @property OpBatch[] $opBatches
 * @property OpBatch[] $opBatches0
 * @property OpBook[] $opBooks
 * @property OpBook[] $opBooks0
 * @property OpBookMovement[] $opBookMovements
 * @property OpBookMovement[] $opBookMovements0
 * @property OpBookPurchase[] $opBookPurchases
 * @property OpBookPurchase[] $opBookPurchases0
 * @property OpBookQueue[] $opBookQueues
 * @property OpBookQueue[] $opBookQueues0
 * @property OpBookQueue[] $opBookQueues1
 * @property OpBookUnit[] $opBookUnits
 * @property OpBookUnit[] $opBookUnits0
 * @property OpClassroom[] $opClassrooms
 * @property OpClassroom[] $opClassrooms0
 * @property OpCourse[] $opCourses
 * @property OpCourse[] $opCourses0
 * @property OpCourseLevel[] $opCourseLevels
 * @property OpCourseLevel[] $opCourseLevels0
 * @property OpCourseParalelo[] $opCourseParalelos
 * @property OpCourseParalelo[] $opCourseParalelos0
 * @property OpCourseParaleloWizard[] $opCourseParaleloWizards
 * @property OpCourseParaleloWizard[] $opCourseParaleloWizards0
 * @property OpCourseTemplate[] $opCourseTemplates
 * @property OpCourseTemplate[] $opCourseTemplates0
 * @property OpExam[] $opExams
 * @property OpExam[] $opExams0
 * @property OpExamAttendees[] $opExamAttendees
 * @property OpExamAttendees[] $opExamAttendees0
 * @property OpExamResAllocation[] $opExamResAllocations
 * @property OpExamResAllocation[] $opExamResAllocations0
 * @property OpExamRoom[] $opExamRooms
 * @property OpExamRoom[] $opExamRooms0
 * @property OpExamSession[] $opExamSessions
 * @property OpExamSession[] $opExamSessions0
 * @property OpExamType[] $opExamTypes
 * @property OpExamType[] $opExamTypes0
 * @property OpExtraValues[] $opExtraValues
 * @property OpExtraValues[] $opExtraValues0
 * @property OpFacility[] $opFacilities
 * @property OpFacility[] $opFacilities0
 * @property OpFacilityLine[] $opFacilityLines
 * @property OpFacilityLine[] $opFacilityLines0
 * @property OpFaculty[] $opFaculties
 * @property OpFaculty[] $opFaculties0
 * @property OpFaculty[] $opFaculties1
 * @property OpFamily[] $opFamilies
 * @property OpFamily[] $opFamilies0
 * @property OpFamilyStudents[] $opFamilyStudents
 * @property OpFamilyStudents[] $opFamilyStudents0
 * @property OpHealth[] $opHealths
 * @property OpHealth[] $opHealths0
 * @property OpHealthLine[] $opHealthLines
 * @property OpHealthLine[] $opHealthLines0
 * @property OpHostel[] $opHostels
 * @property OpHostel[] $opHostels0
 * @property OpHostelRoom[] $opHostelRooms
 * @property OpHostelRoom[] $opHostelRooms0
 * @property OpInstitueTransportService[] $opInstitueTransportServices
 * @property OpInstitueTransportService[] $opInstitueTransportServices0
 * @property OpInstitute[] $opInstitutes
 * @property OpInstitute[] $opInstitutes0
 * @property OpLibraryCard[] $opLibraryCards
 * @property OpLibraryCard[] $opLibraryCards0
 * @property OpLibraryCardType[] $opLibraryCardTypes
 * @property OpLibraryCardType[] $opLibraryCardTypes0
 * @property OpMarksheetLine[] $opMarksheetLines
 * @property OpMarksheetLine[] $opMarksheetLines0
 * @property OpMarksheetRegister[] $opMarksheetRegisters
 * @property OpMarksheetRegister[] $opMarksheetRegisters0
 * @property OpMarksheetRegister[] $opMarksheetRegisters1
 * @property OpMinClearCriteria[] $opMinClearCriterias
 * @property OpMinClearCriteria[] $opMinClearCriterias0
 * @property OpParent[] $opParents
 * @property OpParent[] $opParents0
 * @property OpParent[] $opParents1
 * @property OpPassStatus[] $opPassStatuses
 * @property OpPassStatus[] $opPassStatuses0
 * @property OpPeriod[] $opPeriods
 * @property OpPeriod[] $opPeriods0
 * @property OpPlacementOffer[] $opPlacementOffers
 * @property OpPlacementOffer[] $opPlacementOffers0
 * @property OpPublisher[] $opPublishers
 * @property OpPublisher[] $opPublishers0
 * @property OpResultExamLine[] $opResultExamLines
 * @property OpResultExamLine[] $opResultExamLines0
 * @property OpResultLine[] $opResultLines
 * @property OpResultLine[] $opResultLines0
 * @property OpResultTemplate[] $opResultTemplates
 * @property OpResultTemplate[] $opResultTemplates0
 * @property OpResultTemplateLine[] $opResultTemplateLines
 * @property OpResultTemplateLine[] $opResultTemplateLines0
 * @property OpRollNumber[] $opRollNumbers
 * @property OpRollNumber[] $opRollNumbers0
 * @property OpRoom[] $opRooms
 * @property OpRoom[] $opRooms0
 * @property OpScheduleEnrollment[] $opScheduleEnrollments
 * @property OpScheduleEnrollment[] $opScheduleEnrollments0
 * @property OpScheduleEnrollmentLastname[] $opScheduleEnrollmentLastnames
 * @property OpScheduleEnrollmentLastname[] $opScheduleEnrollmentLastnames0
 * @property OpScholarship[] $opScholarships
 * @property OpScholarship[] $opScholarships0
 * @property OpScholarshipType[] $opScholarshipTypes
 * @property OpScholarshipType[] $opScholarshipTypes0
 * @property OpSection[] $opSections
 * @property OpSection[] $opSections0
 * @property OpStop[] $opStops
 * @property OpStop[] $opStops0
 * @property OpStudent[] $opStudents
 * @property OpStudent[] $opStudents0
 * @property OpStudentAuthorizedParent[] $opStudentAuthorizedParents
 * @property OpStudentAuthorizedParent[] $opStudentAuthorizedParents0
 * @property OpStudentEnrollment[] $opStudentEnrollments
 * @property OpStudentEnrollment[] $opStudentEnrollments0
 * @property OpStudentEnrollmentContract[] $opStudentEnrollmentContracts
 * @property OpStudentEnrollmentContract[] $opStudentEnrollmentContracts0
 * @property OpStudentEnrollmentServices[] $opStudentEnrollmentServices
 * @property OpStudentEnrollmentServices[] $opStudentEnrollmentServices0
 * @property OpStudentInscription[] $opStudentInscriptions
 * @property OpStudentInscription[] $opStudentInscriptions0
 * @property OpSubject[] $opSubjects
 * @property OpSubject[] $opSubjects0
 * @property OpTag[] $opTags
 * @property OpTag[] $opTags0
 * @property OpTransportation[] $opTransportations
 * @property OpTransportation[] $opTransportations0
 * @property OpVehicle[] $opVehicles
 * @property OpVehicle[] $opVehicles0
 * @property OpeneducatConfigSettings[] $openeducatConfigSettings
 * @property OpeneducatConfigSettings[] $openeducatConfigSettings0
 * @property PaymentAcquirer[] $paymentAcquirers
 * @property PaymentAcquirer[] $paymentAcquirers0
 * @property PaymentMethod[] $paymentMethods
 * @property PaymentMethod[] $paymentMethods0
 * @property PaymentTransaction[] $paymentTransactions
 * @property PaymentTransaction[] $paymentTransactions0
 * @property PayslipLinesContributionRegister[] $payslipLinesContributionRegisters
 * @property PayslipLinesContributionRegister[] $payslipLinesContributionRegisters0
 * @property PayslipPaymentWizard[] $payslipPaymentWizards
 * @property PayslipPaymentWizard[] $payslipPaymentWizards0
 * @property PayslipSchedulerWizard[] $payslipSchedulerWizards
 * @property PayslipSchedulerWizard[] $payslipSchedulerWizards0
 * @property PortalWizard[] $portalWizards
 * @property PortalWizard[] $portalWizards0
 * @property PortalWizardUser[] $portalWizardUsers
 * @property PortalWizardUser[] $portalWizardUsers0
 * @property PortalWizardUser[] $portalWizardUsers1
 * @property PrepaymentLine[] $prepaymentLines
 * @property PrepaymentLine[] $prepaymentLines0
 * @property PrepaymentType[] $prepaymentTypes
 * @property PrepaymentType[] $prepaymentTypes0
 * @property PrintPrenumberedChecks[] $printPrenumberedChecks
 * @property PrintPrenumberedChecks[] $printPrenumberedChecks0
 * @property ProcurementGroup[] $procurementGroups
 * @property ProcurementGroup[] $procurementGroups0
 * @property ProcurementOrder[] $procurementOrders
 * @property ProcurementOrder[] $procurementOrders0
 * @property ProcurementOrderComputeAll[] $procurementOrderComputeAlls
 * @property ProcurementOrderComputeAll[] $procurementOrderComputeAlls0
 * @property ProcurementOrderpointCompute[] $procurementOrderpointComputes
 * @property ProcurementOrderpointCompute[] $procurementOrderpointComputes0
 * @property ProcurementRule[] $procurementRules
 * @property ProcurementRule[] $procurementRules0
 * @property ProductAttribute[] $productAttributes
 * @property ProductAttribute[] $productAttributes0
 * @property ProductAttributeLine[] $productAttributeLines
 * @property ProductAttributeLine[] $productAttributeLines0
 * @property ProductAttributePrice[] $productAttributePrices
 * @property ProductAttributePrice[] $productAttributePrices0
 * @property ProductAttributeValue[] $productAttributeValues
 * @property ProductAttributeValue[] $productAttributeValues0
 * @property ProductBrand[] $productBrands
 * @property ProductBrand[] $productBrands0
 * @property ProductCategory[] $productCategories
 * @property ProductCategory[] $productCategories0
 * @property ProductPackaging[] $productPackagings
 * @property ProductPackaging[] $productPackagings0
 * @property ProductPriceHistory[] $productPriceHistories
 * @property ProductPriceHistory[] $productPriceHistories0
 * @property ProductPriceList[] $productPriceLists
 * @property ProductPriceList[] $productPriceLists0
 * @property ProductPricelist[] $productPricelists
 * @property ProductPricelist[] $productPricelists0
 * @property ProductPricelistItem[] $productPricelistItems
 * @property ProductPricelistItem[] $productPricelistItems0
 * @property ProductProduct[] $productProducts
 * @property ProductProduct[] $productProducts0
 * @property ProductPutaway[] $productPutaways
 * @property ProductPutaway[] $productPutaways0
 * @property ProductRemoval[] $productRemovals
 * @property ProductRemoval[] $productRemovals0
 * @property ProductStockLocation[] $productStockLocations
 * @property ProductStockLocation[] $productStockLocations0
 * @property ProductSupplierinfo[] $productSupplierinfos
 * @property ProductSupplierinfo[] $productSupplierinfos0
 * @property ProductTemplate[] $productTemplates
 * @property ProductTemplate[] $productTemplates0
 * @property ProductTemplate[] $productTemplates1
 * @property ProductTemplateTag[] $productTemplateTags
 * @property ProductTemplateTag[] $productTemplateTags0
 * @property ProductUom[] $productUoms
 * @property ProductUom[] $productUoms0
 * @property ProductUomCateg[] $productUomCategs
 * @property ProductUomCateg[] $productUomCategs0
 * @property Profesion[] $profesions
 * @property Profesion[] $profesions0
 * @property PurchaseConfigSettings[] $purchaseConfigSettings
 * @property PurchaseConfigSettings[] $purchaseConfigSettings0
 * @property PurchaseOrder[] $purchaseOrders
 * @property PurchaseOrder[] $purchaseOrders0
 * @property PurchaseOrderLine[] $purchaseOrderLines
 * @property PurchaseOrderLine[] $purchaseOrderLines0
 * @property RelStudentService[] $relStudentServices
 * @property RelStudentService[] $relStudentServices0
 * @property Report[] $reports
 * @property Report[] $reports0
 * @property ReportDecimoCuarto[] $reportDecimoCuartos
 * @property ReportDecimoCuarto[] $reportDecimoCuartos0
 * @property ReportPaperformat[] $reportPaperformats
 * @property ReportPaperformat[] $reportPaperformats0
 * @property ReporteAmountByPartnerWizard[] $reporteAmountByPartnerWizards
 * @property ReporteAmountByPartnerWizard[] $reporteAmountByPartnerWizards0
 * @property ReporteCajaWizard[] $reporteCajaWizards
 * @property ReporteCajaWizard[] $reporteCajaWizards0
 * @property ReporteCajaWizard[] $reporteCajaWizards1
 * @property ResBank[] $resBanks
 * @property ResBank[] $resBanks0
 * @property ResCipherConfig[] $resCipherConfigs
 * @property ResCipherConfig[] $resCipherConfigs0
 * @property ResCompany[] $resCompanies
 * @property ResCompany[] $resCompanies0
 * @property ResCompanyUsersRel[] $resCompanyUsersRels
 * @property ResCompany[] $cs
 * @property ResConfig[] $resConfigs
 * @property ResConfig[] $resConfigs0
 * @property ResConfigInstaller[] $resConfigInstallers
 * @property ResConfigInstaller[] $resConfigInstallers0
 * @property ResConfigSettings[] $resConfigSettings
 * @property ResConfigSettings[] $resConfigSettings0
 * @property ResCountry[] $resCountries
 * @property ResCountry[] $resCountries0
 * @property ResCountryCanton[] $resCountryCantons
 * @property ResCountryCanton[] $resCountryCantons0
 * @property ResCountryCity[] $resCountryCities
 * @property ResCountryCity[] $resCountryCities0
 * @property ResCountryGroup[] $resCountryGroups
 * @property ResCountryGroup[] $resCountryGroups0
 * @property ResCountryNationality[] $resCountryNationalities
 * @property ResCountryNationality[] $resCountryNationalities0
 * @property ResCountryParish[] $resCountryParishes
 * @property ResCountryParish[] $resCountryParishes0
 * @property ResCountrySector[] $resCountrySectors
 * @property ResCountrySector[] $resCountrySectors0
 * @property ResCountryState[] $resCountryStates
 * @property ResCountryState[] $resCountryStates0
 * @property ResCurrency[] $resCurrencies
 * @property ResCurrency[] $resCurrencies0
 * @property ResCurrencyRate[] $resCurrencyRates
 * @property ResCurrencyRate[] $resCurrencyRates0
 * @property ResDisability[] $resDisabilities
 * @property ResDisability[] $resDisabilities0
 * @property ResFont[] $resFonts
 * @property ResFont[] $resFonts0
 * @property ResGroups[] $resGroups
 * @property ResGroups[] $resGroups0
 * @property ResGroupsUsersRel[] $resGroupsUsersRels
 * @property ResGroups[] $gs
 * @property ResLang[] $resLangs
 * @property ResLang[] $resLangs0
 * @property ResPartner[] $resPartners
 * @property ResPartner[] $resPartners0
 * @property ResPartner[] $resPartners1
 * @property ResPartnerBank[] $resPartnerBanks
 * @property ResPartnerBank[] $resPartnerBanks0
 * @property ResPartnerCategory[] $resPartnerCategories
 * @property ResPartnerCategory[] $resPartnerCategories0
 * @property ResPartnerCivilStatus[] $resPartnerCivilStatuses
 * @property ResPartnerCivilStatus[] $resPartnerCivilStatuses0
 * @property ResPartnerClasification[] $resPartnerClasifications
 * @property ResPartnerClasification[] $resPartnerClasifications0
 * @property ResPartnerGender[] $resPartnerGenders
 * @property ResPartnerGender[] $resPartnerGenders0
 * @property ResPartnerTitle[] $resPartnerTitles
 * @property ResPartnerTitle[] $resPartnerTitles0
 * @property ResRequestLink[] $resRequestLinks
 * @property ResRequestLink[] $resRequestLinks0
 * @property ResStore[] $resStores
 * @property ResStore[] $resStores0
 * @property ResStoreUsersRel[] $resStoreUsersRels
 * @property ResStore[] $cs0
 * @property CrmTeam $saleTeam
 * @property MailAlias $alias
 * @property ResCompany $company
 * @property ResPartner $partner
 * @property ResStore $store
 * @property ResUsers $createU
 * @property ResUsers[] $resUsers
 * @property ResUsers $writeU
 * @property ResUsers[] $resUsers0
 * @property StockLocation $xLocation
 * @property ResUsersLog[] $resUsersLogs
 * @property ResUsersLog[] $resUsersLogs0
 * @property ResUsersStockWarehouseRel[] $resUsersStockWarehouseRels
 * @property StockWarehouse[] $stockWarehouses
 * @property ResUsersWebTipRel[] $resUsersWebTipRels
 * @property WebTip[] $webTips
 * @property ReserveBook[] $reserveBooks
 * @property ReserveBook[] $reserveBooks0
 * @property ResourceCalendar[] $resourceCalendars
 * @property ResourceCalendar[] $resourceCalendars0
 * @property ResourceCalendar[] $resourceCalendars1
 * @property ResourceCalendarAttendance[] $resourceCalendarAttendances
 * @property ResourceCalendarAttendance[] $resourceCalendarAttendances0
 * @property ResourceCalendarLeaves[] $resourceCalendarLeaves
 * @property ResourceCalendarLeaves[] $resourceCalendarLeaves0
 * @property ResourceResource[] $resourceResources
 * @property ResourceResource[] $resourceResources0
 * @property ResourceResource[] $resourceResources1
 * @property ReturnBook[] $returnBooks
 * @property ReturnBook[] $returnBooks0
 * @property ReturnDate[] $returnDates
 * @property ReturnDate[] $returnDates0
 * @property SaleAdvancePaymentInv[] $saleAdvancePaymentInvs
 * @property SaleAdvancePaymentInv[] $saleAdvancePaymentInvs0
 * @property SaleConfigSettings[] $saleConfigSettings
 * @property SaleConfigSettings[] $saleConfigSettings0
 * @property SaleOrder[] $saleOrders
 * @property SaleOrder[] $saleOrders0
 * @property SaleOrder[] $saleOrders1
 * @property SaleOrderLine[] $saleOrderLines
 * @property SaleOrderLine[] $saleOrderLines0
 * @property SaleOrderLine[] $saleOrderLines1
 * @property SaleReserveListWizard[] $saleReserveListWizards
 * @property SaleReserveListWizard[] $saleReserveListWizards0
 * @property ScholarisActividadIndagacionCurso[] $scholarisActividadIndagacionCursos
 * @property ScholarisClaseUsuarios[] $scholarisClaseUsuarios
 * @property SriDocumentAuthorization[] $sriDocumentAuthorizations
 * @property SriDocumentAuthorization[] $sriDocumentAuthorizations0
 * @property SriDocumentAuthorizationRank[] $sriDocumentAuthorizationRanks
 * @property SriDocumentAuthorizationRank[] $sriDocumentAuthorizationRanks0
 * @property SriProvDocumentosZabyca[] $sriProvDocumentosZabycas
 * @property SriProvDocumentosZabyca[] $sriProvDocumentosZabycas0
 * @property SriProvSustentosZabyca[] $sriProvSustentosZabycas
 * @property SriProvSustentosZabyca[] $sriProvSustentosZabycas0
 * @property SriTipoDocumentoZabyca[] $sriTipoDocumentoZabycas
 * @property SriTipoDocumentoZabyca[] $sriTipoDocumentoZabycas0
 * @property StockBackorderConfirmation[] $stockBackorderConfirmations
 * @property StockBackorderConfirmation[] $stockBackorderConfirmations0
 * @property StockChangeProductQty[] $stockChangeProductQties
 * @property StockChangeProductQty[] $stockChangeProductQties0
 * @property StockChangeStandardPrice[] $stockChangeStandardPrices
 * @property StockChangeStandardPrice[] $stockChangeStandardPrices0
 * @property StockConfigSettings[] $stockConfigSettings
 * @property StockConfigSettings[] $stockConfigSettings0
 * @property StockFixedPutawayStrat[] $stockFixedPutawayStrats
 * @property StockFixedPutawayStrat[] $stockFixedPutawayStrats0
 * @property StockImmediateTransfer[] $stockImmediateTransfers
 * @property StockImmediateTransfer[] $stockImmediateTransfers0
 * @property StockIncoterms[] $stockIncoterms
 * @property StockIncoterms[] $stockIncoterms0
 * @property StockInventory[] $stockInventories
 * @property StockInventory[] $stockInventories0
 * @property StockInventoryLine[] $stockInventoryLines
 * @property StockInventoryLine[] $stockInventoryLines0
 * @property StockKardexMove[] $stockKardexMoves
 * @property StockKardexMove[] $stockKardexMoves0
 * @property StockKardexMove[] $stockKardexMoves1
 * @property StockKardexWizard[] $stockKardexWizards
 * @property StockKardexWizard[] $stockKardexWizards0
 * @property StockLocation[] $stockLocations
 * @property StockLocation[] $stockLocations0
 * @property StockLocationPath[] $stockLocationPaths
 * @property StockLocationPath[] $stockLocationPaths0
 * @property StockLocationRoute[] $stockLocationRoutes
 * @property StockLocationRoute[] $stockLocationRoutes0
 * @property StockMove[] $stockMoves
 * @property StockMove[] $stockMoves0
 * @property StockMoveOperationLink[] $stockMoveOperationLinks
 * @property StockMoveOperationLink[] $stockMoveOperationLinks0
 * @property StockMoveScrap[] $stockMoveScraps
 * @property StockMoveScrap[] $stockMoveScraps0
 * @property StockPackOperation[] $stockPackOperations
 * @property StockPackOperation[] $stockPackOperations0
 * @property StockPackOperationLot[] $stockPackOperationLots
 * @property StockPackOperationLot[] $stockPackOperationLots0
 * @property StockPicking[] $stockPickings
 * @property StockPicking[] $stockPickings0
 * @property StockPicking[] $stockPickings1
 * @property StockPickingCollectType[] $stockPickingCollectTypes
 * @property StockPickingCollectType[] $stockPickingCollectTypes0
 * @property StockPickingReason[] $stockPickingReasons
 * @property StockPickingReason[] $stockPickingReasons0
 * @property StockPickingRemitionGuide[] $stockPickingRemitionGuides
 * @property StockPickingRemitionGuide[] $stockPickingRemitionGuides0
 * @property StockPickingTransporter[] $stockPickingTransporters
 * @property StockPickingTransporter[] $stockPickingTransporters0
 * @property StockPickingType[] $stockPickingTypes
 * @property StockPickingType[] $stockPickingTypes0
 * @property StockProductionLot[] $stockProductionLots
 * @property StockProductionLot[] $stockProductionLots0
 * @property StockQuant[] $stockQuants
 * @property StockQuant[] $stockQuants0
 * @property StockQuantPackage[] $stockQuantPackages
 * @property StockQuantPackage[] $stockQuantPackages0
 * @property StockReturnPicking[] $stockReturnPickings
 * @property StockReturnPicking[] $stockReturnPickings0
 * @property StockReturnPickingLine[] $stockReturnPickingLines
 * @property StockReturnPickingLine[] $stockReturnPickingLines0
 * @property StockWarehouse[] $stockWarehouses0
 * @property StockWarehouse[] $stockWarehouses1
 * @property StockWarehouseOrderpoint[] $stockWarehouseOrderpoints
 * @property StockWarehouseOrderpoint[] $stockWarehouseOrderpoints0
 * @property StudentAttendance[] $studentAttendances
 * @property StudentAttendance[] $studentAttendances0
 * @property StudentHallTicket[] $studentHallTickets
 * @property StudentHallTicket[] $studentHallTickets0
 * @property StudentMigrate[] $studentMigrates
 * @property StudentMigrate[] $studentMigrates0
 * @property StudentService[] $studentServices
 * @property StudentService[] $studentServices0
 * @property SurveyLabel[] $surveyLabels
 * @property SurveyLabel[] $surveyLabels0
 * @property SurveyMailComposeMessage[] $surveyMailComposeMessages
 * @property SurveyMailComposeMessage[] $surveyMailComposeMessages0
 * @property SurveyPage[] $surveyPages
 * @property SurveyPage[] $surveyPages0
 * @property SurveyQuestion[] $surveyQuestions
 * @property SurveyQuestion[] $surveyQuestions0
 * @property SurveyStage[] $surveyStages
 * @property SurveyStage[] $surveyStages0
 * @property SurveySurvey[] $surveySurveys
 * @property SurveySurvey[] $surveySurveys0
 * @property SurveyUserInput[] $surveyUserInputs
 * @property SurveyUserInput[] $surveyUserInputs0
 * @property SurveyUserInputLine[] $surveyUserInputLines
 * @property SurveyUserInputLine[] $surveyUserInputLines0
 * @property UrlConfig[] $urlConfigs
 * @property UrlConfig[] $urlConfigs0
 * @property UrlEncryption[] $urlEncryptions
 * @property UrlEncryption[] $urlEncryptions0
 * @property UtmCampaign[] $utmCampaigns
 * @property UtmCampaign[] $utmCampaigns0
 * @property UtmMedium[] $utmMedia
 * @property UtmMedium[] $utmMedia0
 * @property UtmSource[] $utmSources
 * @property UtmSource[] $utmSources0
 * @property ValidateAccountMove[] $validateAccountMoves
 * @property ValidateAccountMove[] $validateAccountMoves0
 * @property WebEditorConverterTest[] $webEditorConverterTests
 * @property WebEditorConverterTest[] $webEditorConverterTests0
 * @property WebEditorConverterTestSub[] $webEditorConverterTestSubs
 * @property WebEditorConverterTestSub[] $webEditorConverterTestSubs0
 * @property WebIframePagesPage[] $webIframePagesPages
 * @property WebIframePagesPage[] $webIframePagesPages0
 * @property WebPlanner[] $webPlanners
 * @property WebPlanner[] $webPlanners0
 * @property WebTip[] $webTips0
 * @property WebTip[] $webTips1
 * @property Website[] $websites
 * @property Website[] $websites0
 * @property Website[] $websites1
 * @property WebsiteConfigSettings[] $websiteConfigSettings
 * @property WebsiteConfigSettings[] $websiteConfigSettings0
 * @property WebsiteMenu[] $websiteMenus
 * @property WebsiteMenu[] $websiteMenus0
 * @property WebsiteSeoMetadata[] $websiteSeoMetadatas
 * @property WebsiteSeoMetadata[] $websiteSeoMetadatas0
 * @property WizardIrModelMenuCreate[] $wizardIrModelMenuCreates
 * @property WizardIrModelMenuCreate[] $wizardIrModelMenuCreates0
 * @property WizardMultiChartsAccounts[] $wizardMultiChartsAccounts
 * @property WizardMultiChartsAccounts[] $wizardMultiChartsAccounts0
 * @property WizardOpFaculty[] $wizardOpFaculties
 * @property WizardOpFaculty[] $wizardOpFaculties0
 * @property WizardOpFacultyEmployee[] $wizardOpFacultyEmployees
 * @property WizardOpFacultyEmployee[] $wizardOpFacultyEmployees0
 * @property WizardOpStudent[] $wizardOpStudents
 * @property WizardOpStudent[] $wizardOpStudents0
 * @property WizardReconciliationValidation[] $wizardReconciliationValidations
 * @property WizardReconciliationValidation[] $wizardReconciliationValidations0
 * @property WizardSelectMoveTemplate[] $wizardSelectMoveTemplates
 * @property WizardSelectMoveTemplate[] $wizardSelectMoveTemplates0
 * @property WizardSelectMoveTemplate[] $wizardSelectMoveTemplates1
 * @property WizardSelectMoveTemplateLine[] $wizardSelectMoveTemplateLines
 * @property WizardSelectMoveTemplateLine[] $wizardSelectMoveTemplateLines0
 * @property WizardValuationHistory[] $wizardValuationHistories
 * @property WizardValuationHistory[] $wizardValuationHistories0
 * @property Wkf[] $wkfs
 * @property Wkf[] $wkfs0
 * @property WkfActivity[] $wkfActivities
 * @property WkfActivity[] $wkfActivities0
 * @property WkfTransition[] $wkfTransitions
 * @property WkfTransition[] $wkfTransitions0
 * @property ZabycaImport[] $zabycaImports
 * @property ZabycaImport[] $zabycaImports0
 */
class ResUsers extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'res_users';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['active', 'share', 'chatter_needaction_auto'], 'boolean'],
            [['login', 'company_id', 'partner_id', 'alias_id'], 'required'],
            [['password', 'signature', 'password_crypt'], 'string'],
            [['company_id', 'partner_id', 'create_uid', 'write_uid', 'action_id', 'alias_id', 'sale_team_id', 'store_id', 'x_location_id'], 'default', 'value' => null],
            [['company_id', 'partner_id', 'create_uid', 'write_uid', 'action_id', 'alias_id', 'sale_team_id', 'store_id', 'x_location_id'], 'integer'],
            [['create_date', 'write_date', 'password_write_date'], 'safe'],
            [['login'], 'string', 'max' => 64],
            [['password_hash'], 'string', 'max' => 500],
            [['login'], 'unique'],
            [['sale_team_id'], 'exist', 'skipOnError' => true, 'targetClass' => CrmTeam::className(), 'targetAttribute' => ['sale_team_id' => 'id']],
            [['alias_id'], 'exist', 'skipOnError' => true, 'targetClass' => MailAlias::className(), 'targetAttribute' => ['alias_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => ResCompany::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['partner_id'], 'exist', 'skipOnError' => true, 'targetClass' => ResPartner::className(), 'targetAttribute' => ['partner_id' => 'id']],
            [['store_id'], 'exist', 'skipOnError' => true, 'targetClass' => ResStore::className(), 'targetAttribute' => ['store_id' => 'id']],
            [['create_uid'], 'exist', 'skipOnError' => true, 'targetClass' => ResUsers::className(), 'targetAttribute' => ['create_uid' => 'id']],
            [['write_uid'], 'exist', 'skipOnError' => true, 'targetClass' => ResUsers::className(), 'targetAttribute' => ['write_uid' => 'id']],
            [['x_location_id'], 'exist', 'skipOnError' => true, 'targetClass' => StockLocation::className(), 'targetAttribute' => ['x_location_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'active' => 'Active',
            'login' => 'Login',
            'password' => 'Password',
            'company_id' => 'Company ID',
            'partner_id' => 'Partner ID',
            'create_date' => 'Create Date',
            'create_uid' => 'Create Uid',
            'share' => 'Share',
            'write_uid' => 'Write Uid',
            'write_date' => 'Write Date',
            'signature' => 'Signature',
            'action_id' => 'Action ID',
            'password_crypt' => 'Password Crypt',
            'alias_id' => 'Alias ID',
            'chatter_needaction_auto' => 'Chatter Needaction Auto',
            'sale_team_id' => 'Sale Team ID',
            'store_id' => 'Store ID',
            'password_hash' => 'Password Hash',
            'x_location_id' => 'X Location ID',
            'password_write_date' => 'Password Write Date',
        ];
    }

/**
     * @return \yii\db\ActiveQuery
     */
    public function getPartner()
    {
        return $this->hasOne(ResPartner::className(), ['id' => 'partner_id']);
    }    


}
